sudo: required
dist: trusty
language: c
compiler:
    - gcc
    - clang
os:
    - linux
    - osx

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - libnl-3-200
            - libnl-3-dev
            - libnl-route-3-200
            - libnl-route-3-dev
            - libibverbs-dev
            - librdmacm-dev

env:
    global:
        - AM_MAKEFLAGS="-j4"
        - CPPFLAGS="-I$HOME/bogus/include"
        - LDFLAGS="-I$HOME/bogus/lib"
        - LD_LIBRARY_PATH="$HOME/bogus/lib"
        - CONFIGURE_ARGS="--prefix=$HOME/bogus"
        - DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_ARGS"

# Install dependencies for the verbs and usnic providers.  Open MPI is
# not currently using the verbs provider in Libfabric, so we might as
# well not build it.
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/ofiwg/libfabric.git ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd libfabric && ./autogen.sh && ./configure --prefix=$HOME/bogus --enable-usnic --disable-verbs && make install && cd .. ; fi

install:
    - m4 --version
    - autoconf --version
    - automake --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then libtool --version; else glibtool --version; fi
    - ./autogen.pl
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then ./configure $CONFIGURE_ARGS --with-libfabric=$HOME/bogus --with-usnic --with-verbs; else ./configure $CONFIGURE_ARGS; fi
    - make -k

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then make distcheck; else make check; fi
